spring:
  application:
    name: physio_ai

  datasource:
    url: jdbc:postgresql://localhost:5432/physio_ai
    username: postgres
    password: postgres
    
server:
  host: http://localhost:8080

  flyway:
    locations: classpath:/db/migration
    url: jdbc:postgresql://localhost:5432/physio_ai
    user: postgres
    password: postgres

  data:
    jdbc:
      dialect: postgresql

  docker:
    compose:
      lifecycle-management: start_only

springdoc:
  api-docs:
    enabled: true
    path: /api

debug: false

logging:
  level:
    org.springframework.ai.chat.client.advisor:
      DEBUG

rezepte:
  path: ./rezepte