spring:
  application:
    name: physio_ai

  datasource:
    url: jdbc:postgresql://${PHYSIO_DB_HOST:localhost}:${PHYSIO_DB_PORT:5432}/${PHYSIO_DB_NAME:physio_ai}
    username: ${PHYSIO_DB_USER:postgres}
    password: ${PHYSIO_DB_PASSWORD:postgres}

server:
  port: ${PHYSIO_BACKEND_PORT:8080}

  flyway:
    locations: classpath:/db/migration
    url: jdbc:postgresql://${PHYSIO_DB_HOST:localhost}:${PHYSIO_DB_PORT:5432}/${PHYSIO_DB_NAME:physio_ai}
    user: ${PHYSIO_DB_USER:postgres}
    password: ${PHYSIO_DB_PASSWORD:postgres}

  data:
    jdbc:
      dialect: postgresql

  docker:
    compose:
      lifecycle-management: start_only

springdoc:
  api-docs:
    enabled: true
    path: /api

debug: false

logging:
  level:
    org.springframework.ai.chat.client.advisor:
      DEBUG

rezepte:
  path: ./rezepte